### ISSUE TITLE
Master branch should be the default one

### ISSUE THREAD

**Issue by nandotorterolo** [ScalaConsultants/zionomicon#1]
@mayonesa  Hi John,  I did create a master branch, which should be merged into dev.
I have no access make it default. If you have, please do it for me.

Ronins should checkout master, and start from there. 
Thanks Fernando

**Comment by mayonesa** [comment]
desafortunadamente, tampoco yo tengo permiso de cambiar el default branch. podrías hacer un PR en contra de `dev`?

**Comment by nandotorterolo** [comment]
No, sigo hago un Pr, voy a borrar tu estructura,  y tus ejercicios vas a estar ahi.
La idea seria tener una branch limpia / en blanco
